### ISSUE TITLE
Trying to get setup with Control4

### ISSUE THREAD

**Issue by grabidou** [bphillips09/Control4-HA-Coordinator#3]
I was able to get the control4 driver loaded and connected to HA.  Im unable to add the rest of the configuration.  Do you have a short write up or can point me in the right direction?  super interested in getting this to work with a Ring Alarm into Control4.

**Comment by mikedanie** [comment]
I am not able to connect to home assistant... how did you connect?
![driversettings](https://github.com/bphillips09/Control4-HA-Coordinator/assets/99699026/ae06a2b3-9acb-4d73-ab07-24b78af2f7ed)
![luaerror](https://github.com/bphillips09/Control4-HA-Coordinator/assets/99699026/ea4aa209-7208-4524-801f-1ed56a19d285)

**Comment by grabidou** [comment]
> I am not able to connect to home assistant... how did you connect? ![driversettings](https://user-images.githubusercontent.com/99699026/280560535-ae06a2b3-9acb-4d73-ab07-24b78af2f7ed.png) ![luaerror](https://user-images.githubusercontent.com/99699026/280560556-ea4aa209-7208-4524-801f-1ed56a19d285.png)

Honestly, I installed the driver, added the IP and the Long Lived token.  it connected.  don't really know how to move forward after that. :-)

This is a brand new install of HA.  All that I installed was MQTT and the Ring-MQTT Driver in HA.  then was trying to get this to work to see if I could get the alarm over to C4.

![image](https://github.com/bphillips09/Control4-HA-Coordinator/assets/23324058/10060ea7-0518-4822-931b-3b0938097ce6)

**Comment by grabidou** [comment]
actually, looking at your screenshot, maybe remove the HTTP:// and just use the IP Address:8123

**Comment by bphillips09** [comment]
Hi guys - happy to help!

@mikedanie The "Home Assistant URL" field should just be the IP address and Port, with no URI scheme in front

@grabidou The Coordinator (this driver) only manages the connection between HA and C4 and handles sending data to the other drivers. If you want to integrate your Ring Alarm into C4 using these drivers, first look at what entity types you want to integrate. 

For example, the Ring Alarm integration you're using might provide the following entity types (I don't have one so this is just a guess):
- Alarm Control Panel (Alarm arm/disarm/state/etc)
- Binary Sensor (on/off or open/closed, maybe a door or window contact or a doorbell button)
- Light (any Z-wave lights you have connected to your ring alarm)

You would set up this driver (HA Coordinator) along with the specific drivers for those entities in Home Assistant. So to go along with the examples above, you'd want to install my [HA Alarm Panel](https://github.com/bphillips09/Control4-HA-Alarm-Panel/releases/tag/v1.0.1) driver, [HA Binary Sensor](https://github.com/bphillips09/Control4-HA-Binary-Sensor/releases/tag/v1.0.1) driver, [HA Light](https://github.com/bphillips09/Control4-HA-Light/releases/tag/v1.0.5) driver, etc. These represent the device in C4 with the HA entity ID you set them up with in Composer.

For a list of what your Ring Alarm integration exposes, you can check Home Assistant entities in Home Assistant (Settings > Devices & services > Entities) or in Home Assistant Developer Tools > States.

Hope this helps!

**Comment by mikedanie** [comment]
I tried my HA url without the URL scheme first in front first and again with no luck... I thought this might be because I have DuckDNS and lets_encrypt running.   That is why I included the https

**Comment by bphillips09** [comment]
@mikedanie Gotcha, unfortunately if you want to connect with SSL you'll need to provide your own certs as that is currently a limitation of the C4 driver system. You should still be able to connect without SSL as long as your HA instance allows it.

**Comment by mikedanie** [comment]
@bphillips09 I dont "want" to connect with SSL I just set up DuckDNS years ago in HA for remote access... I will keep playing with this cause i'm not sure how to "provide your own certs"

**Comment by mikedanie** [comment]
@bphillips09 I removed DuckDNS and can now access my HA instance at 192.168.1.7:8123 but the driver can still not connect... not sure what I am missing

**Comment by bphillips09** [comment]
@mikedanie If you can access your instance at that IP and you've set up that IP:Port in the driver, try clicking "Disconnect" then "Connect" in the driver actions. Does it connect?

**Comment by bphillips09** [comment]
For example mine looks like this: ![Screenshot](https://github.com/bphillips09/Control4-HA-Coordinator/assets/8829544/956a14a7-fea4-4985-b4f0-fceb30430ee1)

**Comment by mikedanie** [comment]
@bphillips09 Still does not connect... I restarted HA and C4... Got new token from HA... Still no luck... I've been using chowmain's http driver to interact with HA so I'm gonna have to change all my programming to drop the s from https for my house to function again...LOL

**Comment by grabidou** [comment]
@bphillips09 , I just installed a new instance on a VM in my office.  im having the same issue that @mikedanie is having now.  Brand new install of HA haven't installed any drivers or integrations.

"OnPropertyChanged error: 	driver.lua:195: bad argument #1 to 'pairs' (table expected, got nil)	Home_Assistant_URL"

**Comment by grabidou** [comment]
ok, so here's what I've found @bphillips09 and @mikedanie .  the driver doesnt connect in C4 until you add a Lock, Light, Alarm, or other HA driver to C4.

**Comment by bphillips09** [comment]
@grabidou @mikedanie Good catch! That is definitely a bug with the new version of the driver. Will fix tomorrow!

**Comment by bphillips09** [comment]
In the meantime, [v1.0.5](https://github.com/bphillips09/Control4-HA-Coordinator/releases/tag/v1.0.5) should work fine.

**Comment by mikedanie** [comment]
@bphillips09 @grabidou was right it did connect after adding a light driver.... Response is sluggish but I figure you will figure it out... Thank you both for your help

**Comment by mikedanie** [comment]
@bphillips09 I appologize... The one entity I added seems to be working flawlessly!

**Comment by bphillips09** [comment]
> @grabidou @mikedanie Good catch! That is definitely a bug with the new version of the driver. Will fix tomorrow!

Should be fixed in [v1.0.7](https://github.com/bphillips09/Control4-HA-Coordinator/releases/tag/v1.0.7)

**Comment by bphillips09** [comment]
> @grabidou @mikedanie Good catch! That is definitely a bug with the new version of the driver. Will fix tomorrow!

Should be fixed in [v1.0.7](https://github.com/bphillips09/Control4-HA-Coordinator/releases/tag/v1.0.7)

**Comment by mikedanie** [comment]
@bphillips09 I still only have one entity integrated (Dining Room Light) but I don't have 2-way response.  I can control the light just fine in C4 but if I turn it on manually it does not reflect it C4... is this a known thing?  I WAS able to figure out the DuckDNS https settings
![driversettings1](https://github.com/bphillips09/Control4-HA-Coordinator/assets/99699026/55cd3eb1-c975-4827-ba07-d8848d5d820f)

**Comment by bphillips09** [comment]
@mikedanie Hmmm... that is strange, especially since it is connecting without a CA Certificate. Does it work without SSL enabled? Have you tried assuring it's connected using SSL by using the `Actions` page to Disconnect and Connect again?

If it is in-fact connected then it should work bidirectionally. I would recommend changing the entity ID in your Light driver to something else, then changing it back to your light entity. That will force the Light driver to pull any info from HA if it's connected.

Also feel free to reach out to me on Discord if you want a faster response: @bphillips09#3605

**Comment by dacorn** [comment]
Question on how this manages the entities. Can I control the entities that will be available in control4? I have over 2500 entities and I don't want to kill the C4 controller with garbage entities that will never get used.

**Comment by grabidou** [comment]
> Question on how this manages the entities. Can I control the entities that will be available in control4? I have over 2500 entities and I don't want to kill the C4 controller with garbage entities that will never get used.

This connects C4 with HA. Then @bphillips09 has additional drivers that you can load into C4 for lights, alarm, etc which you put the entity id in. So in short it doenst automatically pull in all entities. Make sense?

**Comment by dacorn** [comment]
Yes totally, I just tried one light and one dimmer as a test worked perfect.  I am very happy with how well this works. I had been using the Berto drivers in the past. I haven't tested color lights yet but I will do that today.

**Comment by dacorn** [comment]
What is the best way to display sensor values from HA? I have a few items I want to display on my panel. Solar generation, Power use, I have other sensors values as well but I haven't found a good way to display them in C4. Any ideas?

**Comment by bphillips09** [comment]
> What is the best way to display sensor values from HA? I have a few items I want to display on my panel. Solar generation, Power use, I have other sensors values as well but I haven't found a good way to display them in C4. Any ideas?

I don't think there is a good built-in way to display generic sensors unless they are temperature or humidity values. You can use them for programming and automations or make a generic driver with custom icons for status.

**Comment by dacorn** [comment]
Ok I will try that, however, I can’t see a way to use the custom icons based on different value ranges. The “experience icons” don’t seem to have this functionality. 

Great job on these I look forward to seeing the new updates on these! Thanks again.

**Comment by dacorn** [comment]
Ok, thats too bad would really allow for a much better UI if we can display
some sensor info. I will continue to keep pestering our rep!

Let me know on the light for making scenes when you have that in beta more
than happy to help test.
