### ISSUE TITLE
SSL needs to be reset after reboot

### ISSUE THREAD

**Issue by blulite** [bphillips09/Control4-HA-Coordinator#7]
I am running version 112 with SSL enabled. When the system is restarted, the connection to Home Assistant fails unless I unselect "Use SSL," save, and then select "Use SSL." Everything works fine until the next system restart.

**Comment by bphillips09** [comment]
@blulite I sent you an updated version of HA Coordinator with a possible fix - were you able to test it and confirm if it fixed your issue?

**Comment by blulite** [comment]
Where did you send the file as I do not have it.

**Comment by bphillips09** [comment]
@blulite I sent it to you as a private message in Discord on 7/21.

**Comment by blulite** [comment]
The new version fixed it!   Thanks!
